version: '3.8'

services:
  mySQL:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mySQL:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mySQL
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8888:80"
    depends_on:
      - mySQL

volumes:
  mySQL:
    driver: local
    driver_opts:
      type: none
      device: ./data/docker/mysql_data
      o: bind