version: '3.8'

services:
  db_trader:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crypto_trader
      MYSQL_USER: trader
      MYSQL_PASSWORD: trader
    ports:
      - "3306:3306"
    volumes:
      - db_trader:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db_trader
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8888:80"
    depends_on:
      - db_trader

volumes:
  db_trader:
