version: '3.8'

services:
  db_trader_pg:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: crypto_trader
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader
    ports:
      - "5432:5432"
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data  # Espelha os dados na pasta /data do projeto

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    depends_on:
      - db_trader_pg
    volumes:
      - ./data/var/lib/pgadmin/:/var/lib/pgadmin/

volumes: {}